# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './DiscgolfBot/appsettings.json'
      env:
        ConnectionStrings.Database: ${{ secrets.CONNECTION_STRING }}
        Discord.Token: ${{ secrets.DISCORD_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore ./DiscgolfBot/DiscgolfBot.sln
    - name: Build
      run: dotnet build ./DiscgolfBot/DiscgolfBot.sln --configuration Release --no-restore
    - name: Publish
      run: dotnet publish ./DiscgolfBot/DiscgolfBot.sln --configuration Release --no-build --output ./publish
    - name: Copy service file if it does not exist
      run: |
        DEST="/etc/systemd/system/discgolfbot.service"
        SRC="./DiscgolfBot/DiscgolfBot/service/discgolfbot.service"
        if [ ! -f "$DEST" ]; then
          echo ${{ secrets.SUDOPWD }} | sudo -S cp "$SRC" "$DEST"
          sudo systemctl daemon-reload
        fi
    - name: Restart service
      run: echo ${{ secrets.SUDOPWD }} | sudo -S systemctl restart DiscGolfBot
